### ISSUE TITLE
not able to connect

### ISSUE THREAD

**Issue by Seidlm** [nibi79/worxlandroid#30]
Hi, i am using windows 10 an openhab 2.5
i am not able to get a connection
Log is here:

2020-05-10 21:40:06.923 [WARN ] [nt.mqtt.AwsIotMqttConnectionListener] - Connect request failure
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190) [org.eclipse.paho.client.mqttv3-1.2.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267) ~[?:1.8.0_232]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[?:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[?:?]
	... 1 more
2020-05-10 21:40:06.927 [ERROR] [d.internal.WorxLandroidBridgeHandler] - Iniialization error - class: com.amazonaws.services.iot.client.AWSIotException
2020-05-10 21:40:06.927 [ERROR] [d.internal.WorxLandroidBridgeHandler] - Iniialization error - message: null
2020-05-10 21:40:06.927 [ERROR] [d.internal.WorxLandroidBridgeHandler] - Iniialization error - stacktrace: [Ljava.lang.StackTraceElement;@36e605e3
2020-05-10 21:40:06.928 [ERROR] [d.internal.WorxLandroidBridgeHandler] - Iniialization error - toString: com.amazonaws.services.iot.client.AWSIotException

**Comment by nibi79** [comment]
Please enable trace log in Karaf console
log:set DEBUG org.openhab.binding.worxlandroid
and post the trace log here or send me the log
