### ISSUE TITLE
OH3: Provide compiled JAR of curdev branch?

### ISSUE THREAD

**Issue by Boby71** [nibi79/worxlandroid#58]
Hi,
would it be possible for you to compile an OH3 compatible JAR file and place it somewhere? 
Without the SDK installed I guess it's not easy to compile them myself, but OH3 got released yesterday and this binding just doesn't work in version 2.5.3

Thank you!

**Comment by nibi79** [comment]
Hi,

because I am currently on the road, I can only test it in my development environment. Can you please test it and give me feedback.

https://github.com/nibi79/worxlandroid/releases/tag/v3.0-beta

Thank you!

**Comment by nibi79** [comment]
Hi @LukasA83,
first of all thank you for your work. Can you please also test my compiled jar?

**Comment by LukasA83** [comment]
Hi nibi, 

right now my mower is on a winter break ;) But basic function seems to work (bridge is connecting and mower is correctly shown as offline).

Hope that helps for the time being.

**Comment by Boby71** [comment]
Looks good! I was able to install the bridge, the movers got discovered automatically. A lot of channels are available and the linking to an item was no problem. Real life tests will be done from April on when the mower is back from the basement into the garden :-). But as far as I can tell, everything seems to work fine - thank you for the quick solution!!!

**Comment by Boby71** [comment]
After upgrading to the latest snapshot (3.1, Build #2111), the binding isn't working anymore unfortunately. It throws the following exception:

```
[2021-01-02 18:53:52.134 [ERROR] [id.internal.WorxLandroidMowerHandler] - RefreshStatusRunnable 201930198403016726AC: Unknown error

org.openhab.binding.worxlandroid.internal.webapi.WebApiException: java.io.IOException: Broken pipe

	at org.openhab.binding.worxlandroid.internal.webapi.request.WebApiRequest.callWebApi(WebApiRequest.java:122) ~[bundleFile:?]

	at org.openhab.binding.worxlandroid.internal.webapi.request.WebApiRequest.callWebApiGet(WebApiRequest.java:79) ~[bundleFile:?]

	at org.openhab.binding.worxlandroid.internal.webapi.request.ProductItemsRequest.call(ProductItemsRequest.java:46) ~[bundleFile:?]

	at org.openhab.binding.worxlandroid.internal.webapi.WorxLandroidWebApiImpl.retrieveUserDevices(WorxLandroidWebApiImpl.java:100) ~[bundleFile:?]

	at org.openhab.binding.worxlandroid.internal.WorxLandroidMowerHandler$1.run(WorxLandroidMowerHandler.java:108) [bundleFile:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:834) [?:?]

Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe

	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:685) ~[bundleFile:9.4.20.v20190813]

	at org.openhab.binding.worxlandroid.internal.webapi.request.WebApiRequest.callWebApi(WebApiRequest.java:92) ~[bundleFile:?]

	... 10 more

Caused by: java.io.IOException: Broken pipe

	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:928) ~[?:?]

	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[?:?]

	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[?:?]

	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[?:?]

	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:249) ~[?:?]

	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:62) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:85) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:128) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:201) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:252) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:121) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:346) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:304) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:294) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:269) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:246) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:580) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:728) ~[bundleFile:9.4.20.v20190813]

	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:681) ~[bundleFile:9.4.20.v20190813]

	at org.openhab.binding.worxlandroid.internal.webapi.request.WebApiRequest.callWebApi(WebApiRequest.java:92) ~[bundleFile:?]

	... 10 more](url)
```

**Comment by nibi79** [comment]
hi, please take a look to this issue: https://github.com/nibi79/worxlandroid/issues/4

**Comment by Boby71** [comment]
Thank you!

**Comment by Boby71** [comment]
after the latest snaphot-update, it stopped working again:

```
2021-01-10 21:25:18.137 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.worxlandroid-3.0.0-SNAPSHOT.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.worxlandroid [46]

  Unresolved requirement: Import-Package: org.openhab.core.config.discovery

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
```

**Comment by Boby71** [comment]
Don't know why, but it works again. Closing this issue again.
