### ISSUE TITLE
HANDLER_INITIALIZING_ERROR

### ISSUE THREAD

**Issue by simonvrsic** [nibi79/worxlandroid#99]
Dear.

Error to make handler 
HANDLER_INITIALIZING_ERROR
multiple points 

2023-08-31 22:02:17.085 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'worxlandroid:mower:955e0974ba:202130267110005836E8': multiple points
java.lang.NumberFormatException: multiple points
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:?]
        at java.lang.Float.parseFloat(Float.java:455) ~[?:?]
        at org.openhab.binding.worxlandroid.internal.WorxLandroidMowerHandler.initialize(WorxLandroidMowerHandler.java:227) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by clinique** [comment]
This error comes from a change in the format of the firmware version number (it has to be handled as a string).
I it solved in the v4 but correction has to be backported to v3

**Comment by simonvrsic** [comment]
Can you provide us V4 download?

**Comment by clinique** [comment]
Here https://drive.google.com/file/d/1EU4APg4nf0R4uqrqOMzbjqeSXFeCEeg8/view?usp=drive_link

**Comment by martinlindjarv** [comment]
Will V4 work with openhab 3.4 as well or is there any possibility or timeline that this fix will be backported to v3?

**Comment by clinique** [comment]
No v4 will not work with oh 3.4. Yes it can easily be backported by anyone volonteering. I'll do not because I'm working only on current release.

**Comment by martinlindjarv** [comment]
I had a look, but my java knowledge can be defined with "not existing" ... can someone with more knowledge than mine fix it :)?
I'm happy to test the package.

**Comment by TomW80** [comment]
I would also be happy about the adaptation for openhab 3.4. But unfortunately can not contribute code either

**Comment by mauerj** [comment]
I created a fix that at least works for me to bring the device back online. Archive provided under -> releases in my repo.

**Comment by Incom0de** [comment]
Thanks mauerj,
On my Installation status is online now. Hope that everything is working.

**Comment by mauerj** [comment]
> Thanks mauerj, On my Installation status ob bridge is online now. Hope that everything is working.

rain_delay, rain_delay_start and one_time_scheduler are the only features that are compared agains the version and might be afected by the fix. Unfortunately, I cannot test any of these.
